Add validation, sidebar, login. Improve design.
Dev-incubator/DIMS-UI-10 pull request #2
Opened 2020-10-05 14:55 UTC by VadimAlkhimenok

2020-10-06 15:57 UTC, maximsan requested changes
Hello! Left some notes. Please fix them! Thanks!

2020-10-06 15:57 UTC, maximsan commented on src/components/auth/Auth.js
> +    if (isCorrectPassword(this.state.email, this.state.password)) {
I believe the condition should be apposite if the password is correct

2020-10-06 15:57 UTC, maximsan commented on src/components/auth/Auth.js
> +    return this.auth();
don't see a  real need to create a method for this

2020-10-06 15:57 UTC, maximsan commented on src/components/modals/modal-register/ModalRegister.js
> +    console.log('true', isEmptyInput(this.state));
remove

2020-10-06 15:57 UTC, maximsan commented on src/components/modals/modal-register/ModalRegister.js
> +                key={idx}
don't use method index as a key

2020-10-06 15:57 UTC, maximsan commented on src/components/modals/modal-template/ModalTemplate.module.css
> +  height: 109%;
looks weird

2020-10-06 15:57 UTC, maximsan commented on src/components/select/Select.js
> +          <option key={`${index}select`}>{option}</option>
I will propose you to use this `'${option}${index}'`  as a key

2020-10-06 15:57 UTC, maximsan commented on src/components/side-bar/side-bar-main/SidebarMain.js
> +          </li>
why do you not use `Link` from 'react-router-dom' ?

2020-10-06 15:57 UTC, maximsan commented on src/pages/member-progress/MemberProgress.js
> +        <Lines key={`${progress.userTaskId}progress`}>
`userTaskId` is enough I believe

2020-10-06 15:57 UTC, maximsan commented on src/pages/members-tasks/MemberTasks.js
> +          <Lines key={`${task.taskId}task`}>
taskId is enough

2020-10-06 15:57 UTC, maximsan commented on src/pages/members/Members.js
> +            <Line width={3} text={index + 1} />
userId is enough

2020-10-06 15:57 UTC, maximsan commented on src/components/auth/validation/ValidationAuth.js
> +};
add unit tests

2020-10-06 15:57 UTC, maximsan commented on src/components/auth/validation/ValidationAuth.js
> +};
add unit tests

2020-10-07 20:32 UTC, VadimAlkhimenok commented on src/components/auth/Auth.js
> +    if (isCorrectPassword(this.state.email, this.state.password)) {
Done.

2020-10-07 20:33 UTC, VadimAlkhimenok commented on src/components/auth/Auth.js
> +    return this.auth();
Done.

2020-10-07 20:34 UTC, VadimAlkhimenok commented on src/components/modals/modal-register/ModalRegister.js
> +    console.log('true', isEmptyInput(this.state));
Done.

2020-10-07 20:36 UTC, VadimAlkhimenok commented on src/pages/members/Members.js
> +            <Line width={3} text={index + 1} />
Done.

2020-10-07 20:37 UTC, VadimAlkhimenok commented on src/pages/members-tasks/MemberTasks.js
> +          <Lines key={`${task.taskId}task`}>
Done.

2020-10-07 20:38 UTC, VadimAlkhimenok commented on src/pages/member-progress/MemberProgress.js
> +        <Lines key={`${progress.userTaskId}progress`}>
Done.

2020-10-07 20:39 UTC, VadimAlkhimenok commented on src/components/side-bar/side-bar-main/SidebarMain.js
> +          </li>
Done.

2020-10-07 20:40 UTC, VadimAlkhimenok commented on src/components/select/Select.js
> +          <option key={`${index}select`}>{option}</option>
Done.

2020-10-12 13:34 UTC, VadimAlkhimenok commented on src/components/modals/modal-template/ModalTemplate.module.css
> +  height: 109%;
Done.

2020-10-12 13:35 UTC, VadimAlkhimenok commented on src/components/modals/modal-register/ModalRegister.js
> +                key={idx}
Done.

2020-10-13 14:39 UTC, maximsan approved these changes
Hello, please don't forget to remove extra files, add them to ignore. I will approve and merge it.

2020-10-13 14:39 UTC, maximsan commented on .idea/DIMS-UI-10.iml
> +</module>
add to gitignore, delete from repo

2020-10-13 14:39 UTC, maximsan commented on .idea/codeStyles/Project.xml
> +</component>
add to gitignore, delete from repo

2020-10-13 14:39 UTC, maximsan commented on .idea/codeStyles/codeStyleConfig.xml
> +</component>
add to gitignore, delete from repo

2020-10-13 14:39 UTC, maximsan commented on .idea/misc.xml
> +</project>
add to gitignore, delete from repo

2020-10-13 14:39 UTC, maximsan commented on .idea/modules.xml
> +</project>
add to gitignore, delete from repo

2020-10-13 14:39 UTC, maximsan commented on .idea/vcs.xml
> +</project>
add to gitignore, delete from repo

2020-10-13 14:39 UTC, merged